#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$ROOT_DIR/build"

echo "==> Cleaning build directory"
rm -rf "$BUILD_DIR"

mkdir -p "$BUILD_DIR"

echo "==> Copying configuration"
cp "$ROOT_DIR/configuration.yaml" "$BUILD_DIR/configuration.yaml"

echo "==> Copying packages"
if [[ -d "$ROOT_DIR/packages" ]]; then
    cp -R "$ROOT_DIR/packages" "$BUILD_DIR/packages"
fi

echo "==> Copying blueprints"
if [[ -d "$ROOT_DIR/blueprints" ]]; then
    cp -R "$ROOT_DIR/blueprints" "$BUILD_DIR/blueprints"
fi

echo "==> Copying themes"
if [[ -d "$ROOT_DIR/themes" ]]; then
    cp -R "$ROOT_DIR/themes" "$BUILD_DIR/themes"
fi

echo "==> Building automations.yaml"

{
    echo "# Generated by build.sh — DO NOT EDIT"
    echo
} > "$BUILD_DIR/automations.yaml"

while IFS= read -r -d '' file; do
    sed '1s/^/- /; 2,$s/^/  /' "$file"
    echo
done < <(
    find "$ROOT_DIR/automations" \
        -type f \
        -name '*.yaml' \
        -print0 |
    sort -z
) >> "$BUILD_DIR/automations.yaml"

echo "==> Building scripts.yaml"

{
    echo "# Generated by build.sh — DO NOT EDIT"
    echo
} > "$BUILD_DIR/scripts.yaml"

while IFS= read -r -d '' file; do
    name="$(basename "$file" .yaml)"

    echo "$name:"
    sed 's/^/  /' "$file"
    echo
done < <(
    find "$ROOT_DIR/scripts" \
        -type f \
        -name '*.yaml' \
        -print0 |
    sort -z
) >> "$BUILD_DIR/scripts.yaml"

echo "==> Building scenes.yaml"

{
    echo "# Generated by build.sh — DO NOT EDIT"
    echo
} > "$BUILD_DIR/scenes.yaml"

if [[ -d "$ROOT_DIR/scenes" ]]; then
    while IFS= read -r -d '' file; do
        sed '1s/^/- /; 2,$s/^/  /' "$file"
        echo
    done < <(
        find "$ROOT_DIR/scenes" \
            -type f \
            -name '*.yaml' \
            -print0 |
        sort -z
    ) >> "$BUILD_DIR/scenes.yaml"
else
    echo "[]" >> "$BUILD_DIR/scenes.yaml"
fi

echo
echo "==> Build complete"
echo "    Output: $BUILD_DIR"
