alias: Natural Lights - MàJ temps réel
description: Met à jour Natural Light dans les pièces activées
triggers:
  - trigger: time_pattern
    minutes: /5
actions:
  - repeat:
      for_each: "{{ areas() }}"
      sequence:
        - variables:
            natural_light_helper: |
              {{ area_entities(repeat.item)
                 | select('match', '^input_boolean\\..*_natural_lights$')
                 | list
                 | first
                 | default('', true) }}
        - condition: template
          value_template: |
            {{ natural_light_helper != ''
               and is_state(natural_light_helper, 'on') }}
        - action: script.turn_on
          target:
            entity_id: script.natural_light
          data:
            variables:
              area: "{{ repeat.item }}"
mode: single
