alias: Natural Light — Activation
description: Active ou désactive Natural Light pour une pièce
triggers:
  - trigger: state
    entity_id:
      - input_boolean.salon_natural_lights
      - input_boolean.bureau_natural_lights
      - input_boolean.chambre_natural_lights
actions:
  - variables:
      area: "{{ area_id(trigger.entity_id) }}"
  - condition: template
    value_template: "{{ area != none }}"
  - variables:
      active_lights: |
        {{ expand(area_entities(area))
           | selectattr('domain', 'eq', 'light')
           | selectattr('state', 'eq', 'on')
           | map(attribute='entity_id')
           | list }}
  - condition: template
    value_template: "{{ active_lights | length > 0 }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ active_lights }}"
            data:
              brightness_pct: 20
              transition: 0.1
          - delay:
              milliseconds: 100
          - action: script.turn_on
            target:
              entity_id: script.natural_light
            data:
              variables:
                area: "{{ area }}"
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ active_lights }}"
            data:
              brightness_pct: 20
              transition: 0.1
          - delay:
              milliseconds: 100
          - action: light.turn_on
            target:
              entity_id: "{{ active_lights }}"
            data:
              color_temp_kelvin: 4500
              brightness_pct: 100
              transition: 1
mode: parallel
